/**
 * Application-wide constants
 */

export const LAYOUT_CONSTANTS = {
  CONTROLS_HEIGHT: "144px",
  HEADER_HEIGHT: "97px",
  DEFAULT_PANEL_SIZE: 70,
  CONVERSATION_PANEL_SIZE: 60,
  SCREENSHARE_PANEL_SIZE: 40,
  LOGS_PANEL_SIZE: 30,
  MIN_PANEL_SIZE_SMALL: 20,
  MIN_PANEL_SIZE_MEDIUM: 30,
  MIN_PANEL_SIZE_LARGE: 40,
} as const;

export const EVENT_STREAM_CONFIG = {
  MAX_EVENTS: 500,
  TRUNCATE_LENGTH: 100,
  SCROLL_THROTTLE_MS: 100,
} as const;

export const UI_CONFIG = {
  AUDIO_VISUALIZER_BAR_COUNT: 5,
  VIDEO_WIDTH: 256, // w-64 = 256px
} as const;
